export const STORAGE_KEY = "matchup-demo-state-v2";
export const EVENT_NAME = "matchup:state-change";
export const LOYALTY_POLICY = Object.freeze({
  earnPerAmount: 1000,
  pointValue: 100,
  maxDiscountRate: 0.5,
});
export const WALLET_PAYMENT_METHOD = "Ví MatchUp";
export const FREE_MATCH_LIMIT = 5;
export const FREE_SAVED_MATCH_LIMIT = 10;
export const FREE_CHAT_ROOM_LIMIT = 3;
export const FREE_HOLD_MINUTES = 10;
export const PREMIUM_HOLD_MINUTES = 30;
export const LOYALTY_PREMIUM_MULTIPLIER = 2;
export const PREMIUM_PLANS = Object.freeze([
  {
    id: "monthly",
    label: "Premium Tháng",
    price: 60000,
    days: 30,
    unitLabel: "tháng",
    description: "Thanh toán hằng tháng, hủy bất cứ lúc nào",
    badge: "Phổ biến nhất",
  },
  {
    id: "yearly",
    label: "Premium Năm",
    price: 600000,
    days: 365,
    unitLabel: "năm",
    description: "Tiết kiệm bằng 2 tháng phí so với trả theo tháng",
    badge: "Tiết kiệm 17%",
  },
]);
export const PREMIUM_BENEFITS = Object.freeze([
  {
    icon: "all_inclusive",
    title: "Xin vào kèo không giới hạn",
    description: "Miễn phí 5 trận/tháng, Premium thoải mái tìm kèo.",
  },
  {
    icon: "sell",
    title: "Ưu đãi đặt sân độc quyền",
    description: "Voucher Premium riêng cho thành viên khi đặt sân.",
  },
  {
    icon: "timer",
    title: "Giữ chỗ sân lâu hơn",
    description: "Giữ sân tới 30 phút thay vì 10 phút để kịp mời đội.",
  },
  {
    icon: "card_membership",
    title: "Tích điểm x2",
    description: "Nhân đôi điểm thành viên khi thanh toán qua MatchUp.",
  },
  {
    icon: "bookmark",
    title: "Lưu kèo không giới hạn",
    description: "Gói miễn phí lưu tối đa 10 kèo, Premium lưu thoải mái.",
  },
  {
    icon: "calendar_month",
    title: "Voucher 30.000đ mỗi tháng",
    description: "Ưu đãi đặt sân quay vòng hằng tháng cho thành viên.",
  },
  {
    icon: "star",
    title: "Kèo nổi bật",
    description: "Kèo do bạn tạo được gắn huy hiệu và lên đầu danh sách.",
  },
  {
    icon: "forum",
    title: "Chat không giới hạn",
    description: "Gói miễn phí giữ 3 phòng chat, Premium giữ không giới hạn.",
  },
  {
    icon: "tune",
    title: "Bộ lọc & gợi ý nâng cao",
    description: "Lọc theo chất lượng đội và mở rộng bán kính 20 km.",
  },
  {
    icon: "workspace_premium",
    title: "Huy hiệu Premium",
    description: "Nổi bật trong danh sách thành viên, ưu tiên khi duyệt.",
  },
]);
export const SPORT_LABELS = Object.freeze({
  football: "bóng đá",
  badminton: "cầu lông",
  pickleball: "pickleball",
  basketball: "bóng rổ",
});
export const VOUCHER_CATALOG = Object.freeze([
    {
      id: "welcome20",
      code: "MATCH20",
      category: "new",
      categoryLabel: "Tân thủ",
      icon: "celebration",
      tone: "yellow",
      title: "Giảm 20% lần đặt sân đầu",
      description: "Áp dụng cho mọi sân đối tác",
      condition: "Đơn từ 120.000đ",
      expires: "Hết hạn 31/08",
      expiresAt: "2026-08-31T23:59:59+07:00",
      discountType: "percent",
      discountValue: 20,
      maxDiscount: 80000,
      minSpend: 120000,
      requiresFirstBooking: true,
      priority: 1,
    },
    {
      id: "offpeak50",
      code: "OFFPEAK50",
      category: "offpeak",
      categoryLabel: "Giờ thấp điểm",
      icon: "wb_sunny",
      tone: "orange",
      title: "Giảm 50.000đ giờ thấp điểm",
      description: "Thứ 2–6 · 06:00–17:00",
      condition: "Đơn từ 150.000đ",
      expires: "Hết hạn 15/09",
      expiresAt: "2026-09-15T23:59:59+07:00",
      discountType: "fixed",
      discountValue: 50000,
      minSpend: 150000,
      weekdayOnly: true,
      timeRange: { start: 6, end: 17 },
      priority: 2,
    },
    {
      id: "football30",
      code: "FOOTBALL30",
      category: "sport",
      categoryLabel: "Theo môn",
      icon: "sports_soccer",
      tone: "green",
      title: "Bóng đá giảm 30.000đ",
      description: "Dành riêng cho sân bóng đá",
      condition: "Đơn từ 180.000đ",
      expires: "Hết hạn 30/09",
      expiresAt: "2026-09-30T23:59:59+07:00",
      discountType: "fixed",
      discountValue: 30000,
      minSpend: 180000,
      sports: ["football"],
      priority: 3,
    },
    {
      id: "badminton15",
      code: "RACKET15",
      category: "sport",
      categoryLabel: "Theo môn",
      icon: "sports",
      tone: "blue",
      title: "Cầu lông giảm 15%",
      description: "Cho mọi sân cầu lông đối tác",
      condition: "Giảm tối đa 40.000đ",
      expires: "Hết hạn 30/09",
      expiresAt: "2026-09-30T23:59:59+07:00",
      discountType: "percent",
      discountValue: 15,
      maxDiscount: 40000,
      sports: ["badminton"],
      priority: 4,
    },
    {
      id: "pickleball40",
      code: "PICKLE40",
      category: "sport",
      categoryLabel: "Theo môn",
      icon: "sports_tennis",
      tone: "purple",
      title: "Pickleball giảm 40.000đ",
      description: "Thử sân pickleball gần bạn",
      condition: "Đơn từ 140.000đ",
      expires: "Hết hạn 30/09",
      expiresAt: "2026-09-30T23:59:59+07:00",
      discountType: "fixed",
      discountValue: 40000,
      minSpend: 140000,
      sports: ["pickleball"],
      priority: 5,
    },
    {
      id: "friends30",
      code: "TEAM30",
      category: "friends",
      categoryLabel: "Bạn bè",
      icon: "group",
      tone: "red",
      title: "Rủ đủ đội, giảm 30.000đ",
      description: "Khi nhóm có từ 4 người",
      condition: "Đơn từ 180.000đ",
      expires: "Hết hạn 30/09",
      expiresAt: "2026-09-30T23:59:59+07:00",
      discountType: "fixed",
      discountValue: 30000,
      minSpend: 180000,
      minTeamSize: 4,
      priority: 6,
    },
    {
      id: "premium60",
      code: "PREMIUM60",
      category: "premium",
      categoryLabel: "Premium",
      icon: "workspace_premium",
      tone: "gold",
      title: "Premium giảm 60.000đ đặt sân",
      description: "Ưu đãi độc quyền cho thành viên Premium",
      condition: "Đơn từ 200.000đ",
      expires: "Hết hạn 31/12",
      expiresAt: "2026-12-31T23:59:59+07:00",
      discountType: "fixed",
      discountValue: 60000,
      minSpend: 200000,
      requiresPremium: true,
      priority: 0,
    },
    {
      id: "premium30",
      code: "PREMIUM30",
      category: "premium",
      categoryLabel: "Premium",
      icon: "calendar_month",
      tone: "gold",
      title: "Giảm 30.000đ mỗi tháng",
      description: "Voucher quay vòng hằng tháng cho thành viên Premium",
      condition: "Đơn từ 150.000đ · 1 lần/tháng",
      expires: "Quay vòng mỗi tháng",
      discountType: "fixed",
      discountValue: 30000,
      minSpend: 150000,
      requiresPremium: true,
      monthly: true,
      priority: 1,
    },
]);
